version: '3.9'
# Docker Compose file for a simple Node.js server with MongoDB

services:
  mongo:
    # use the official MongoDB image
    image: mongo:7
    # restart policy to always restart the container
    restart: always
    # port mapping
    ports:
      - "${MONGO_PORT:-27017}:27017"
    # volume to persist data  
    volumes:
      - mongo-data:/data/db
  server:
    # build the Node.js server from the Dockerfile in the server directory
    build: ./server
    # environment variables from the .env file
    env_file: ./server/.env
    ports:
      - "${SERVER_PORT:-5002}:5001"
    # depends_on ensures the server starts after MongoDB
    depends_on:
      - mongo
volumes:
  # Define a named volume for MongoDB data persistence
  mongo-data: